name: Python CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y fluidsynth ffmpeg

    - name: Download soundfont
      run: |
        wget -O soundfont.sf2 "https://github.com/FluidSynth/fluidsynth/raw/master/sf2/VintageDreamsWaves-v2.sf2"

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install -e .

    - name: Run unit and core logic tests
      run: |
        pytest tests/test_server_basic.py
        # Run our Phase 2 tests which will create and save MIDI files
        python test_phase_2.py

    - name: Run E2E composition analysis tests
      run: |
        pytest tests/e2e/test_composition_analysis.py -v

